In this project we will detect fraudulent credit card transactions with the help of Machine learning models.
We will analyse customer-level data that has been collected and analysed during a research collaboration of Worldline and the Machine Learning Group.

In [1]:
#importing dependencies
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib as plt

In [2]:
cc=pd.read_csv('creditcard.csv')
cc

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [3]:
cc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [4]:
##checking for null values
cc.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
##checking the legit transaction and fraud transaction
cc['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [6]:
leg=cc[cc.Class==0]
frad=cc[cc.Class==1]
print(leg.shape)
print(frad.shape)

(284315, 31)
(492, 31)

In [7]:
##statistical measure of the data
leg.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [8]:
frad.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [9]:
#now we will compare both 
cc.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [10]:
##Now i will take the random 492 no of data from legit in so that we have equal distribution of data
leg_sa=leg.sample(n=492)
leg_sa

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
160797,113637.0,2.087643,-1.163560,-0.842536,-0.970517,-0.801168,-0.264593,-0.864202,-0.099805,0.133754,...,-0.066286,-0.330100,0.192405,-1.024796,-0.384280,-0.430843,-0.002051,-0.037391,85.00,0
156328,107871.0,-0.608477,0.857120,2.113395,-0.278924,0.173275,0.242693,0.262651,0.129122,1.116831,...,-0.218199,-0.379918,-0.295915,-0.498836,0.294092,-0.693892,0.080804,0.063447,11.27,0
259313,159057.0,2.054434,-0.055046,-1.065016,0.408257,-0.108971,-1.128484,0.171683,-0.310901,0.535062,...,-0.283312,-0.672495,0.346988,-0.012343,-0.312146,0.201005,-0.067248,-0.060514,1.29,0
120912,76005.0,-0.388652,1.091329,1.266915,0.012234,0.225675,-0.504321,0.658446,0.052362,-0.431967,...,-0.232078,-0.557623,0.018633,0.028268,-0.225186,0.100772,0.262556,0.095535,5.99,0
93266,64324.0,1.089127,-0.566166,1.084087,0.219099,-1.319702,-0.443614,-0.625578,0.044828,1.133872,...,-0.082112,-0.209625,0.005614,0.463105,0.077567,0.984211,-0.048787,0.027250,74.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269742,163751.0,-0.938582,0.438543,1.334676,-1.421734,-0.218807,-0.155700,-0.298362,0.756300,0.555133,...,0.245350,0.507238,-0.106373,-0.452099,-0.523848,-0.659761,0.064354,0.084672,4.13,0
18479,29536.0,0.504863,-1.253485,1.233692,1.838676,-1.510599,0.542698,-0.475897,0.324040,1.335541,...,-0.059366,-0.424279,-0.237853,0.553899,0.337297,-0.482318,0.027156,0.074388,295.00,0
49617,44136.0,0.668268,-2.393175,0.067394,-1.128434,-1.769088,-0.086951,-0.602388,-0.123690,-1.768510,...,-0.108924,-0.885685,-0.207585,-0.310173,-0.048408,-0.403438,-0.020805,0.096409,435.70,0
248816,154108.0,-7.027628,6.582920,-5.101593,-1.130280,-2.842417,-1.889184,-2.095521,3.408525,1.959091,...,0.242686,1.008772,0.559081,-0.022872,0.335422,-0.174026,0.828533,0.628775,0.89,0
107584,70508.0,-1.686989,-0.101418,2.550502,0.437575,0.286650,0.047540,0.180268,0.183117,-0.022634,...,0.250541,0.747843,-0.128527,0.124383,0.540880,-0.309718,-0.053513,0.201997,95.00,0

In [11]:
#Now i will contantinate both the data
new_cc=pd.concat([leg_sa,frad],axis=0)
new_cc

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
160797,113637.0,2.087643,-1.163560,-0.842536,-0.970517,-0.801168,-0.264593,-0.864202,-0.099805,0.133754,...,-0.066286,-0.330100,0.192405,-1.024796,-0.384280,-0.430843,-0.002051,-0.037391,85.00,0
156328,107871.0,-0.608477,0.857120,2.113395,-0.278924,0.173275,0.242693,0.262651,0.129122,1.116831,...,-0.218199,-0.379918,-0.295915,-0.498836,0.294092,-0.693892,0.080804,0.063447,11.27,0
259313,159057.0,2.054434,-0.055046,-1.065016,0.408257,-0.108971,-1.128484,0.171683,-0.310901,0.535062,...,-0.283312,-0.672495,0.346988,-0.012343,-0.312146,0.201005,-0.067248,-0.060514,1.29,0
120912,76005.0,-0.388652,1.091329,1.266915,0.012234,0.225675,-0.504321,0.658446,0.052362,-0.431967,...,-0.232078,-0.557623,0.018633,0.028268,-0.225186,0.100772,0.262556,0.095535,5.99,0
93266,64324.0,1.089127,-0.566166,1.084087,0.219099,-1.319702,-0.443614,-0.625578,0.044828,1.133872,...,-0.082112,-0.209625,0.005614,0.463105,0.077567,0.984211,-0.048787,0.027250,74.95,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [12]:
new_cc['Class'].value_counts()

1    492
0    492
Name: Class, dtype: int64

In [13]:
new_cc.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96854.436992,-0.065582,-0.075012,0.018878,-0.040353,-0.027715,-0.078496,0.026855,-0.002054,-0.112896,...,-0.016968,0.027806,0.026717,-0.060933,0.000217,-0.004358,0.008586,-0.011924,-0.002047,103.421626
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [14]:
#now split the data into features and target
x=new_cc.drop(columns='Class',axis=1)
y=new_cc['Class']

In [15]:
#train_test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
model=LogisticRegression().fit(x_train,y_train)
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
y_pred=model.predict(x_test)

In [30]:
##accuracy on test data
score=metrics.accuracy_score(y_pred,y_test)

In [31]:
score

0.9238578680203046

In [32]:
##accuracy on training data 
ytrain_pred=model.predict(x_train)
score=metrics.accuracy_score(ytrain_pred,y_train)
score

0.9199491740787802